config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  #get "event/index" => "event#index"

  resources :event, only: [:index, :show, :create, :destroy]
  resources :week, only: [:show, :create, :destroy] do
    resources :comment, only: [:create, :destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :week
  #belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  #has_many :weeks, dependent: :destroy
  #has_many :comments, dependent: :destroy
end

app/models/week.rb
class Week < ApplicationRecord
  #belongs_to :event
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    comment.week_id = Week.find(params[:week_id])
    #comment.event_id = 
    comment.save
    redirect_to request.referer
  end

  def destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
    @event = Event.all
    @date = Date.today
    @date2 = Date.today + 7
    @date3 = Date.today + 14
  end

  def show
    #@event = Event.find(params[:id])
    @week = Week.find(params[:id])
  end

  def create
    event = Event.new(event_params)
    event.save
    redirect_to request.referer
  end

  def destroy
  end

  private
  def event_params
    params.require(:event).permit(:start, :finish)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/week_controller.rb
class WeekController < ApplicationController


  def show
    @id = params[:id]
    @week = Week.all
    @date = Date.today
    @date2 = Date.today + 7
    @date3 = Date.today + 14

  end

  def create
    week = Week.new(week_params)
    #week.event_id = Event.find(params[:event_id]).id
    week.save!
    redirect_to request.referer
  end

  def destroy
    Week.find(params[:id]).destroy
    redirect_to request.referer
  end
  
  private

  def week_params
    params.require(:week).permit(:time1, :event_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/week_helper.rb
module WeekHelper
end

app/views/event/index.html.erb
<h1>Event#index</h1>
<br>
<%= form_with model: Event.new, url: event_index_path, method: :post do |f| %>
  <%= f.date_field :start %>
  <%= f.date_field :finish %>
  <%= f.submit "送信"%>
<% end %>
<br>
<% @event.each do |event| %>
  <table>
    <tr>
      <td>
        <%= link_to week_path(event.id) do %>
          <%= event.start %>
          ～
          <%= event.finish %>
        <% end %>
      </td>
    </tr>
  </table>
<% end %>
<%= Event.all.each do |t| %>
<% end %>
<hr>
<table>
  <tr>
    <th>月曜日</th>
    <th>火曜日</th>
    <th>水曜日</th>
    <th>木曜日</th>
    <th>金曜日</th>
    <th>土曜日</th>
    <th>日曜日</th>
  </tr>
  <tr>
    <td><%= (@date +(8-@date.wday)) %></td>
    <td><%= (@date +(9-@date.wday)) %></td>
    <td><%= (@date +(10-@date.wday)) %></td>
    <td><%= (@date +(11-@date.wday)) %></td>
    <td><%= (@date +(12-@date.wday)) %></td>
    <td><%= (@date +(13-@date.wday)) %></td>
    <td><%= (@date +(14-@date.wday)) %></td>
  </tr>
</table>
<hr>
<table>
  <tr>
    <th></th>
    <th>月曜日</th>
    <th>火曜日</th>
    <th>水曜日</th>
    <th>木曜日</th>
    <th>金曜日</th>
    <th>土曜日</th>
    <th>日曜日</th>
  </tr>
  <tr>
    <td>
      <%= link_to week_path(1) do %>
        <%= (@date + (8-@date.wday)).month %>月<%= (@date + (8-@date.wday)).day %>日～
        <%= (@date + (14-@date.wday)).month %>月<%= (@date + (14-@date.wday)).day %>日
      <% end %>
    </td>
    <td><%= (@date + (8-@date.wday)).month %>月<%= (@date + (8-@date.wday)).day %>日</td>
    <td><%= (@date + (9-@date.wday)).month %>月<%= (@date + (9-@date.wday)).day %>日</td>
    <td><%= (@date + (10-@date.wday)).month %>月<%= (@date + (10-@date.wday)).day %>日</td>
    <td><%= (@date + (11-@date.wday)).month %>月<%= (@date + (11-@date.wday)).day %>日</td>
    <td><%= (@date + (12-@date.wday)).month %>月<%= (@date + (12-@date.wday)).day %>日</td>
    <td><%= (@date + (13-@date.wday)).month %>月<%= (@date + (13-@date.wday)).day %>日</td>
    <td><%= (@date + (14-@date.wday)).month %>月<%= (@date + (14-@date.wday)).day %>日</td>
  </tr>
  <tr>
    <td>
      <%= link_to week_path(2) do %>
        <%= (@date2 + (8-@date2.wday)).month %>月<%= (@date2 + (8-@date2.wday)).day %>日～
        <%= (@date2 + (14-@date2.wday)).month %>月<%= (@date2 + (14-@date2.wday)).day %>日
      <% end %>
    </td>
    <td><%= (@date2 + (8-@date2.wday)).month %>月<%= (@date2 + (8-@date2.wday)).day %>日</td>
    <td><%= (@date2 + (9-@date2.wday)).month %>月<%= (@date2 + (9-@date2.wday)).day %>日</td>
    <td><%= (@date2 + (10-@date2.wday)).month %>月<%= (@date2 + (10-@date2.wday)).day %>日</td>
    <td><%= (@date2 + (11-@date2.wday)).month %>月<%= (@date2 + (11-@date2.wday)).day %>日</td>
    <td><%= (@date2 + (12-@date2.wday)).month %>月<%= (@date2 + (12-@date2.wday)).day %>日</td>
    <td><%= (@date2 + (13-@date2.wday)).month %>月<%= (@date2 + (13-@date2.wday)).day %>日</td>
    <td><%= (@date2 + (14-@date2.wday)).month %>月<%= (@date2 + (14-@date2.wday)).day %>日</td>
  </tr>
  <tr>
    <td>
      <%= link_to week_path(3) do %>
        <%= (@date3 + (8-@date3.wday)).month %>月<%= (@date3 + (8-@date3.wday)).day %>日～
        <%= (@date3 + (14-@date3.wday)).month %>月<%= (@date3 + (14-@date3.wday)).day %>日
      <% end %>
    </td>
    <td><%= (@date3 + (8-@date3.wday)).month %>月<%= (@date3 + (8-@date3.wday)).day %>日</td>
    <td><%= (@date3 + (9-@date3.wday)).month %>月<%= (@date3 + (9-@date3.wday)).day %>日</td>
    <td><%= (@date3 + (10-@date3.wday)).month %>月<%= (@date3 + (10-@date3.wday)).day %>日</td>
    <td><%= (@date3 + (11-@date3.wday)).month %>月<%= (@date3 + (11-@date3.wday)).day %>日</td>
    <td><%= (@date3 + (12-@date3.wday)).month %>月<%= (@date3 + (12-@date3.wday)).day %>日</td>
    <td><%= (@date3 + (13-@date3.wday)).month %>月<%= (@date3 + (13-@date3.wday)).day %>日</td>
    <td><%= (@date3 + (14-@date3.wday)).month %>月<%= (@date3 + (14-@date3.wday)).day %>日</td>
  </tr>
</table>

app/views/event/show.html.erb
<h1><%= @week.id %>のページ</h1>
<br>
<%= @week.time1 %>
<%= link_to "削除", week_path(@week.id), data: { turbo_method: :delete } %>
<hr>
<% @week.comments.each do |comment| %>
  <% comment.comment %>
<% end %>
<br>
<%= form_with model:[@week, Comment.new], url:week_comment_index_path(@week.id), method: :post do |f| %>
  <%= f.text_area :comment, placeholder: "ここに書いてね" %>
  <%= f.submit "送信" %>
<% end %>

app/views/homes/top.html.erb
<h1>トップだよ</h1>
<p>Find me in app/views/homes/top.html.erb</p>

<%= link_to "一覧ページ" , event_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Collender</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/week/_table.html.erb
<table>
  <tr>
    <th>月曜日</th>
    <th>火曜日</th>
    <th>水曜日</th>
    <th>木曜日</th>
    <th>金曜日</th>
    <th>土曜日</th>
    <th>日曜日</th>
  </tr>
  <tr>
    <td><%= (date + (8-date.wday)).month %>月<%= (date + (8-date.wday)).day %>日</td>
    <td><%= (date + (9-date.wday)).month %>月<%= (date + (9-date.wday)).day %>日</td>
    <td><%= (date + (10-date.wday)).month %>月<%= (date + (10-date.wday)).day %>日</td>
    <td><%= (date + (11-date.wday)).month %>月<%= (date + (11-date.wday)).day %>日</td>
    <td><%= (date + (12-date.wday)).month %>月<%= (date + (12-date.wday)).day %>日</td>
    <td><%= (date + (13-date.wday)).month %>月<%= (date + (13-date.wday)).day %>日</td>
    <td><%= (date + (14-date.wday)).month %>月<%= (date + (14-date.wday)).day %>日</td>
  </tr>
</table>

<hr>

<%= week_path %>

    <%= Week.all.each do |t| %>
      <%= t.time1 %>
      <%= link_to "削除", week_path(t.id), data: { turbo_method: :delete } %>
    <% end %>
      

app/views/week/show.html.erb
<h1>Week#show</h1>
<p>Find me in app/views/week/show.html.erb</p>
<%= link_to "戻る", event_index_path %>
<hr>

<%= @id %>
<%= Event.find(params[:id]).id %>
<%= form_with model: Week.new, url: week_index_path, method: :post do |f| %>
    <%= f.select :time1, [["〇","〇"],["×","×"],["△","△"]], include_blank: "記号を選んでー" %>
    <%= f.submit "送信" %>
<% end %>
<%= Week.all.each do |t| %>
  <%= link_to event_path(t.id) do %>
    <%= t.time1 %>
  <% end %>
  　<%= link_to "削除", week_path(t.id), data: { turbo_method: :delete } %>
    <br>
<% end %>
<hr>

<% if params[:id] == "1" %>
  1
<hr>
<%= render "table", date: @date, week: @week %>
<hr>
<%= link_to "更新",request.referer %>
<%= Event.all.each do |t| %>
<% end %>

<% end %>

<% if params[:id] == "2" %>
  2
  <%= render "table", date: @date2 %>  
<% end %>

<% if params[:id] == "3" %>
  3
  <%= render "table", date: @date3 %>
<% end %>